<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Maisha HabitsSeeder — Comprehensive Build Habits Edition
 *
 * Total: 60 build habits across 11 categories
 *
 * Theoretical basis:
 *   - Atomic Habits (Clear, 2018): cue embedded in habit name, identity-based framing
 *   - The Power of Habit (Duhigg, 2012): keystone habits flagged with is_keystone=true
 *   - Tiny Habits (Fogg, 2019): difficulty=easy habits are the starter "tiny version"
 *   - Implementation Intention (Gollwitzer, 1999): names written as "When X, do Y"
 *
 * habit_direction: build (do more of this)
 * See QuitHabitsSeeder for quit/limit habits
 */
class HabitsSeeder extends Seeder
{
    public function run(): void
    {
        $habits = [

            // ═══════════════════════════════════════════════════════════════
            // MORNING ROUTINE (7 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Make your bed immediately after waking up',
                'name_sw' => 'Panga kitanda mara baada ya kuamka',
                'category' => 'morning_routine', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '2 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'weight_loss', 'muscle_gain', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Do not check your phone for the first 30 minutes after waking',
                'name_sw' => 'Usishike simu kwa dakika 30 za kwanza baada ya kuamka',
                'category' => 'morning_routine', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'morning',
                'duration_estimate' => '30 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Drink a glass of water when you wake up',
                'name_sw' => 'Kunywa glasi ya maji ukiamka',
                'category' => 'morning_routine', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'kidney_disease']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain', 'muscle_gain', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Write 3 intentions for the day each morning',
                'name_sw' => 'Andika nia 3 za siku kila asubuhi',
                'category' => 'morning_routine', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'save_money', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Say a positive affirmation aloud each morning',
                'name_sw' => 'Sema maneno ya motisha kila asubuhi',
                'category' => 'morning_routine', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Stretch for 5 minutes after waking up',
                'name_sw' => 'Nyoosha mwili dakika 5 ukiamka',
                'category' => 'morning_routine', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'muscle_gain', 'weight_loss']),
                'is_system' => true,
            ],
            [
                'name'    => 'Eat breakfast before 9 AM',
                'name_sw' => 'Kula breakfast kabla ya saa tatu asubuhi',
                'category' => 'morning_routine', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '10 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain', 'manage_condition']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // FITNESS (9 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Put on your workout clothes after waking up',
                'name_sw' => 'Vaa nguo za mazoezi ukiamka',
                'category' => 'fitness', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['weight_loss', 'muscle_gain', 'maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Do 10 push-ups or squats before breakfast',
                'name_sw' => 'Fanya push-up au squat 10 kabla ya breakfast',
                'category' => 'fitness', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '2 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['weight_loss', 'muscle_gain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Walk for 30 minutes today',
                'name_sw' => 'Tembea dakika 30 leo',
                'category' => 'fitness', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'morning',
                'duration_estimate' => '30 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Take a 10-minute walk after lunch',
                'name_sw' => 'Tembea dakika 10 baada ya chakula cha mchana',
                'category' => 'fitness', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'after_meal',
                'duration_estimate' => '10 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['weight_loss', 'manage_condition', 'maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Complete a 20-minute workout today',
                'name_sw' => 'Kamilisha mazoezi ya dakika 20 leo',
                'category' => 'fitness', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'morning',
                'duration_estimate' => '20 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain', 'muscle_gain', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Do a 45-minute strength or gym workout',
                'name_sw' => 'Fanya mazoezi ya nguvu ya dakika 45',
                'category' => 'fitness', 'habit_direction' => 'build',
                'difficulty' => 'hard', 'trigger_time' => 'morning',
                'duration_estimate' => '45 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['muscle_gain', 'weight_loss']),
                'is_system' => true,
            ],
            [
                'name'    => 'Take the stairs instead of the lift',
                'name_sw' => 'Panda ngazi badala ya lifti leo',
                'category' => 'fitness', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'anytime',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['hypertension', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Reach 7,000 steps today',
                'name_sw' => 'Fikia hatua 7,000 leo',
                'category' => 'fitness', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'anytime',
                'duration_estimate' => '60 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Do yoga or flexibility training for 20 minutes',
                'name_sw' => 'Fanya yoga au mazoezi ya kunyumbulika kwa dakika 20',
                'category' => 'fitness', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'morning',
                'duration_estimate' => '20 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'manage_condition']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // NUTRITION (8 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Add a vegetable to your lunch today',
                'name_sw' => 'Weka mboga kwenye chakula chako cha mchana',
                'category' => 'nutrition', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'after_meal',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Cook at home today instead of buying outside',
                'name_sw' => 'Pika nyumbani leo badala ya kununua nje',
                'category' => 'nutrition', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'midday',
                'duration_estimate' => '30 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['save_money', 'weight_loss', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Eat protein before your carbohydrates at each meal',
                'name_sw' => 'Kula protini kabla ya wanga kwa kila mlo',
                'category' => 'nutrition', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'after_meal',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes']),
                'recommended_for_goals' => json_encode(['manage_condition', 'weight_loss']),
                'is_system' => true,
            ],
            [
                'name'    => 'Plan tomorrow\'s meals tonight',
                'name_sw' => 'Panga chakula cha kesho usiku huu',
                'category' => 'nutrition', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'evening',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['save_money', 'weight_loss', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Eat a source of iron today (beans, lentils, or kunde)',
                'name_sw' => 'Kula chanzo cha chuma leo — maharagwe, dengu, au kunde',
                'category' => 'nutrition', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'after_meal',
                'duration_estimate' => '10 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['anaemia']),
                'recommended_for_goals' => json_encode(['manage_condition', 'maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Eat a fibre-rich meal today',
                'name_sw' => 'Kula chakula chenye nyuzinyuzi leo',
                'category' => 'nutrition', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'after_meal',
                'duration_estimate' => '10 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['high_cholesterol', 'diabetes']),
                'recommended_for_goals' => json_encode(['weight_loss', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Eat at least 3 meals at regular times today',
                'name_sw' => 'Kula milo 3 angalau kwa nyakati za kawaida leo',
                'category' => 'nutrition', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'anytime',
                'duration_estimate' => '30 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'ulcer']),
                'recommended_for_goals' => json_encode(['manage_condition', 'maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Avoid eating after 8 PM tonight',
                'name_sw' => 'Usiwe na chakula baada ya saa mbili usiku',
                'category' => 'nutrition', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'evening',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['weight_loss', 'manage_condition']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // HYDRATION (5 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Drink 8 glasses of water today',
                'name_sw' => 'Kunywa glasi 8 za maji leo',
                'category' => 'hydration', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'anytime',
                'duration_estimate' => '2 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'kidney_disease', 'anaemia']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain', 'muscle_gain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Drink water before every meal today',
                'name_sw' => 'Kunywa maji kabla ya kila mlo leo',
                'category' => 'hydration', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'after_meal',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension']),
                'recommended_for_goals' => json_encode(['weight_loss', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Carry a water bottle when you leave home',
                'name_sw' => 'Beba chupa ya maji unapotoka nyumbani',
                'category' => 'hydration', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'weight_loss', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Drink herbal tea instead of a second coffee',
                'name_sw' => 'Kunywa chai ya mitishamba badala ya kahawa ya pili',
                'category' => 'hydration', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'midday',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['hypertension', 'ulcer']),
                'recommended_for_goals' => json_encode(['manage_condition', 'maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Drink a glass of water before bed',
                'name_sw' => 'Kunywa glasi ya maji kabla ya kulala',
                'category' => 'hydration', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'before_sleep',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['hypertension', 'kidney_disease']),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // SLEEP (6 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Be in bed by 10 PM tonight',
                'name_sw' => 'Kuwa kitandani saa nne usiku',
                'category' => 'sleep', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'before_sleep',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Put your phone in another room at bedtime',
                'name_sw' => 'Weka simu chumba kingine wakati wa kulala',
                'category' => 'sleep', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'before_sleep',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Do a 5-minute wind-down routine before sleep',
                'name_sw' => 'Fanya utaratibu wa dakika 5 wa kupumzika kabla ya kulala',
                'category' => 'sleep', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'before_sleep',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Avoid heavy food after 8 PM',
                'name_sw' => 'Epuka chakula kizito baada ya saa mbili usiku',
                'category' => 'sleep', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'evening',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'high_cholesterol', 'ulcer']),
                'recommended_for_goals' => json_encode(['weight_loss', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Wake up at the same time every day',
                'name_sw' => 'Amka wakati mmoja kila siku',
                'category' => 'sleep', 'habit_direction' => 'build',
                'difficulty' => 'hard', 'trigger_time' => 'morning',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'weight_loss', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Sleep 7–8 hours tonight',
                'name_sw' => 'Lala masaa 7–8 usiku huu',
                'category' => 'sleep', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'before_sleep',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['weight_loss', 'maintain', 'muscle_gain']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // MINDFULNESS (6 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Meditate for 5 minutes after waking up',
                'name_sw' => 'Tafakari dakika 5 ukiamka',
                'category' => 'mindfulness', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode(['hypertension', 'diabetes']),
                'recommended_for_goals' => json_encode(['manage_condition', 'maintain', 'weight_loss']),
                'is_system' => true,
            ],
            [
                'name'    => 'Meditate for 20 minutes today',
                'name_sw' => 'Tafakari dakika 20 leo',
                'category' => 'mindfulness', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'morning',
                'duration_estimate' => '20 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode(['hypertension', 'diabetes']),
                'recommended_for_goals' => json_encode(['manage_condition', 'maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Write 3 things you are grateful for tonight',
                'name_sw' => 'Andika vitu 3 unavyoshukuru usiku huu',
                'category' => 'mindfulness', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'before_sleep',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Take 5 slow deep breaths when you feel stressed',
                'name_sw' => 'Pumua polepole mara 5 ukihisi msongo',
                'category' => 'mindfulness', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'anytime',
                'duration_estimate' => '2 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['hypertension', 'diabetes']),
                'recommended_for_goals' => json_encode(['manage_condition', 'maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Spend 10 minutes in silence or prayer today',
                'name_sw' => 'Tumia dakika 10 katika ukimya au sala leo',
                'category' => 'mindfulness', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '10 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Do a body scan to check how you are feeling today',
                'name_sw' => 'Fanya ukaguzi wa mwili kujua hisia zako leo',
                'category' => 'mindfulness', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '2 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension']),
                'recommended_for_goals' => json_encode(['manage_condition', 'maintain']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // LEARNING (6 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Read 10 pages of a book today',
                'name_sw' => 'Soma kurasa 10 za kitabu leo',
                'category' => 'learning', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'evening',
                'duration_estimate' => '20 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Read 30 minutes today',
                'name_sw' => 'Soma kwa dakika 30 leo',
                'category' => 'learning', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'evening',
                'duration_estimate' => '30 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Spend 15 minutes learning something new today',
                'name_sw' => 'Tumia dakika 15 kujifunza kitu kipya leo',
                'category' => 'learning', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'anytime',
                'duration_estimate' => '15 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Practice a language for 10 minutes today',
                'name_sw' => 'Zoea lugha kwa dakika 10 leo',
                'category' => 'learning', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'anytime',
                'duration_estimate' => '10 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Listen to an educational podcast during your commute',
                'name_sw' => 'Sikiliza podcast ya kuelimisha unaposafiri',
                'category' => 'learning', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '20 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Complete one lesson of an online course this week',
                'name_sw' => 'Kamilisha somo moja la kozi ya mtandaoni wiki hii',
                'category' => 'learning', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'evening',
                'duration_estimate' => '30 min', 'frequency' => 'weekly',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'save_money']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // PRODUCTIVITY & JOURNALING (6 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Write in your journal for 5 minutes today',
                'name_sw' => 'Andika kwenye jarida lako kwa dakika 5 leo',
                'category' => 'productivity', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'evening',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'save_money', 'manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Write your top 3 tasks for tomorrow before sleeping',
                'name_sw' => 'Andika kazi 3 za kesho kabla ya kulala',
                'category' => 'productivity', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'before_sleep',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'save_money']),
                'is_system' => true,
            ],
            [
                'name'    => 'Do a 25-minute focused work block (no distractions)',
                'name_sw' => 'Fanya kazi kwa makini kwa dakika 25 bila usumbufu',
                'category' => 'productivity', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'morning',
                'duration_estimate' => '25 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'save_money']),
                'is_system' => true,
            ],
            [
                'name'    => 'Review and clear your to-do list at end of day',
                'name_sw' => 'Kagua na safisha orodha yako ya kazi mwisho wa siku',
                'category' => 'productivity', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'evening',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Tidy your workspace for 5 minutes before starting work',
                'name_sw' => 'Safisha mahali pako pa kazi kwa dakika 5 kabla ya kuanza',
                'category' => 'productivity', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Do a weekly review every Sunday evening',
                'name_sw' => 'Fanya mapitio ya wiki kila Jumapili usiku',
                'category' => 'productivity', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'evening',
                'duration_estimate' => '20 min', 'frequency' => 'weekly',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain', 'save_money']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // SOCIAL & RELATIONSHIPS (4 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Call or message a friend or family member today',
                'name_sw' => 'Piga simu au tuma ujumbe kwa rafiki au familia leo',
                'category' => 'social', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'evening',
                'duration_estimate' => '10 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Do one act of kindness for someone today',
                'name_sw' => 'Fanya tendo moja la wema kwa mtu leo',
                'category' => 'social', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'anytime',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Have a meal with family or friends this week',
                'name_sw' => 'Kula chakula na familia au marafiki wiki hii',
                'category' => 'social', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'after_meal',
                'duration_estimate' => '30 min', 'frequency' => 'weekly',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Put your phone away during meals with others',
                'name_sw' => 'Weka simu wakati wa kula na wengine',
                'category' => 'social', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'after_meal',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // FINANCE (5 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Log every food expense in Maisha today',
                'name_sw' => 'Rekodi kila gharama ya chakula kwenye Maisha leo',
                'category' => 'finance', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'after_meal',
                'duration_estimate' => '2 min', 'frequency' => 'daily',
                'is_keystone' => true,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['save_money']),
                'is_system' => true,
            ],
            [
                'name'    => 'Stay within your daily food budget today',
                'name_sw' => 'Kaa ndani ya bajeti yako ya chakula ya leo',
                'category' => 'finance', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'anytime',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['save_money']),
                'is_system' => true,
            ],
            [
                'name'    => 'Transfer a small amount to savings today',
                'name_sw' => 'Hamisha kiasi kidogo kwenye akiba leo',
                'category' => 'finance', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '2 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['save_money']),
                'is_system' => true,
            ],
            [
                'name'    => 'Review this week\'s spending every Sunday',
                'name_sw' => 'Kagua matumizi ya wiki hii kila Jumapili',
                'category' => 'finance', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'evening',
                'duration_estimate' => '10 min', 'frequency' => 'weekly',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['save_money']),
                'is_system' => true,
            ],
            [
                'name'    => 'Bring food from home instead of buying lunch today',
                'name_sw' => 'Leta chakula kutoka nyumbani badala ya kununua chakula cha mchana',
                'category' => 'finance', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'morning',
                'duration_estimate' => '15 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['save_money', 'weight_loss', 'manage_condition']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // CREATIVITY (3 habits)
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Spend 15 minutes on a creative activity today',
                'name_sw' => 'Tumia dakika 15 kwa shughuli ya ubunifu leo',
                'category' => 'creativity', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'evening',
                'duration_estimate' => '15 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Write one paragraph of free writing today',
                'name_sw' => 'Andika aya moja ya maandishi huru leo',
                'category' => 'creativity', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '5 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],
            [
                'name'    => 'Practice a musical instrument for 15 minutes',
                'name_sw' => 'Zoea ala ya muziki kwa dakika 15',
                'category' => 'creativity', 'habit_direction' => 'build',
                'difficulty' => 'medium', 'trigger_time' => 'evening',
                'duration_estimate' => '15 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode([]),
                'recommended_for_goals' => json_encode(['maintain']),
                'is_system' => true,
            ],

            // ═══════════════════════════════════════════════════════════════
            // HEALTH (medical/condition) — 5 habits
            // ═══════════════════════════════════════════════════════════════

            [
                'name'    => 'Take your medication at the correct time today',
                'name_sw' => 'Kula dawa yako kwa wakati unaohitajika leo',
                'category' => 'health', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Check and log your blood sugar today',
                'name_sw' => 'Pima na rekodi sukari ya damu leo',
                'category' => 'health', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '2 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes']),
                'recommended_for_goals' => json_encode(['manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Check your blood pressure today',
                'name_sw' => 'Pima shinikizo la damu leo',
                'category' => 'health', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'morning',
                'duration_estimate' => '2 min', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['hypertension']),
                'recommended_for_goals' => json_encode(['manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Take your iron supplement with orange juice today',
                'name_sw' => 'Kula kirutubisho cha chuma na maji ya chungwa leo',
                'category' => 'health', 'habit_direction' => 'build',
                'difficulty' => 'easy', 'trigger_time' => 'after_meal',
                'duration_estimate' => 'instant', 'frequency' => 'daily',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['anaemia']),
                'recommended_for_goals' => json_encode(['manage_condition']),
                'is_system' => true,
            ],
            [
                'name'    => 'Attend your health checkup appointment this week',
                'name_sw' => 'Hudhuria miadi yako ya afya wiki hii',
                'category' => 'health', 'habit_direction' => 'build',
                'difficulty' => 'hard', 'trigger_time' => 'anytime',
                'duration_estimate' => '60 min', 'frequency' => 'weekly',
                'is_keystone' => false,
                'recommended_for_conditions' => json_encode(['diabetes', 'hypertension', 'anaemia', 'kidney_disease', 'high_cholesterol']),
                'recommended_for_goals' => json_encode(['manage_condition']),
                'is_system' => true,
            ],

        ]; // end $habits

        foreach ($habits as $habit) {
            DB::table('habits')->insertOrIgnore(array_merge($habit, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('✓ Habits seeded (build): ' . count($habits) . ' items');
        $this->command->info('  Categories: morning_routine(7), fitness(9), nutrition(8), hydration(5)');
        $this->command->info('             sleep(6), mindfulness(6), learning(6), productivity(6)');
        $this->command->info('             social(4), finance(5), creativity(3), health(5)');
    }
}